import { jsPDF } from 'jspdf';
import { TripData } from '../types';

export const generatePDF = (tripData: TripData): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(tripData.trip_meta.title, pageWidth / 2, y, { align: 'center' });
  y += 10;

  // Vibe tags
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(tripData.trip_meta.vibe_tags.join(' | '), pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Line separator
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Days
  tripData.daily_flow.forEach((day) => {
    // Check if we need a new page
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    // Day header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text(`Day ${day.day_num}: ${day.theme}`, margin, y);
    y += 8;

    // Get pins for this day
    const dayPins = tripData.map_pins.filter(p => p.day_index === day.day_num);

    // Sort by time slot
    const timeOrder: Record<string, number> = { 'Morning': 1, 'Lunch': 2, 'Afternoon': 3, 'Dinner': 4 };
    dayPins.sort((a, b) => (timeOrder[a.time_slot] || 5) - (timeOrder[b.time_slot] || 5));

    dayPins.forEach((pin) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      // Time slot
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(230, 100, 100);
      doc.text(pin.time_slot.toUpperCase(), margin, y);

      // Rating and cost
      const ratingText = `★ ${pin.rating?.toFixed(1) || '4.0'} | ${pin.cost_tier}`;
      doc.setTextColor(150, 150, 150);
      doc.text(ratingText, pageWidth - margin, y, { align: 'right' });
      y += 5;

      // Place name
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(50, 50, 50);
      doc.text(pin.name, margin, y);
      y += 5;

      // Description
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      const descLines = doc.splitTextToSize(pin.short_description, pageWidth - 2 * margin);
      doc.text(descLines, margin, y);
      y += descLines.length * 4 + 3;

      // Logistics note
      if (pin.logistics_note) {
        doc.setFontSize(8);
        doc.setTextColor(130, 130, 130);
        doc.text(`→ ${pin.logistics_note}`, margin + 5, y);
        y += 6;
      }

      y += 3;
    });

    y += 5;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by TripArchitect', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  // Save
  doc.save(`${tripData.trip_meta.title.replace(/\s+/g, '_')}_Itinerary.pdf`);
};
